version: "3.5"

services:
  server:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: "adminer"
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"

volumes:
  db_data:
